[build]
python-version = "3.10"

[phases.install]
commands = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "python3 -m ensurepip --upgrade",
    "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/gunicorn library_project.wsgi:application" 