[build]
python-version = "3.10" # You can adjust this to your specific Python version if needed

[phases.setup]
commands = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn library_project.wsgi:application" 